### ISSUE TITLE
Is there a way to get this to work on Windows?

### ISSUE THREAD

**Issue by ruikaitang** [HelloShagun/SentinelOrbit#3]
When I try to run this script on windows using command prompt instead of terminal I get an error on unexpected extra arguments. See screenshot below.
![image](https://user-images.githubusercontent.com/14314580/122294791-6d728400-cec6-11eb-8bc9-7581b94af5a5.png)

**Comment by HelloShagun** [comment]
Hi, I just tried on windows and it worked for me.  Make sure that you have the Sentinel-1 zip files and orbit_solved.py are stored in the same directory.

**Comment by ruikaitang** [comment]
Hmm I tried that but it didn't work. It would make the orbits folder but wouldn't populate it.

Regardless, this issue is fixed by updating SNAP to 8.0.4/8.0.5 so the problem is solved for me anyways.

**Comment by HelloShagun** [comment]
@ruikaitang, that's great. 
by setting up a new conda environment and running the script there solves the issue.
